apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-inventory
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-inventory
  template:
    metadata:
      labels:
        app: ms-inventory
    spec:
      containers:
        - name: ms-inventory
          image: rinsler/oms-ms-inventory:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: ms-inventory
spec:
  type: ClusterIP
  selector:
    app: ms-inventory
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
